### ISSUE TITLE
errores durante la lectura de audio/status

### ISSUE THREAD

**Issue by Rsantct** [AudioHumLab/FIRtro#44]
Se observa A VECES una interrupción al final de initfirtro.py, que deja el server funcionanado pero interrumpe los ajustes finales de inifirtro.py.

Capturado con `sudo journalctl`:

```
09:11:48: (initfirtro) Esperando al SERVER (0s) ....................
09:11:48: (client.py) Connecting to localhost port 9999...
09:11:48: (client.py) Connected
09:11:48: (client.py) Closing connection...
09:11:48: (initfirtro) Ha arrancado el SERVER :-)
09:11:48: (client.py) Connecting to localhost port 9999...
09:11:48: (client.py) Connected
09:11:48: (client.py) Closing connection...
09:11:48: (client.py) Connecting to localhost port 9999...
09:11:48: (client.py) Connected
09:11:48: (client.py) Closing connection...
09:11:48: (client.py) Connecting to localhost port 9999...
09:11:48: (client.py) Connected
09:11:48: (client.py) Closing connection...
09:11:48: Traceback (most recent call last):
09:11:48:   File "/home/firtro/bin/initfirtro.py", line 455, in <module>
09:11:48:     main(run_level)
09:11:48:   File "/home/firtro/bin/initfirtro.py", line 397, in main
09:11:48:     status.readfp(statusfile)
09:11:48:   File "/usr/lib/python2.7/ConfigParser.py", line 324, in readfp
09:11:48:     self._read(fp, filename)
09:11:48:   File "/usr/lib/python2.7/ConfigParser.py", line 512, in _read
09:11:48:     raise MissingSectionHeaderError(fpname, lineno, line)
09:11:48: ConfigParser.MissingSectionHeaderError: File contains no section headers.
09:11:48: file: /home/firtro/audio/status, line: 1
09:11:48: 'f\n'
```

Extracto de initfirtro.py:

```
    ...
    ...
    391         # v2.0 PRESETS: recuperamos el preset por DEFECTO (si estuviera declarado)
    392         if default_preset:
    393             client.firtro_socket("preset " + default_preset)
    394         else:
    395             client.firtro_socket("preset " + preset)
    396         # y nos ponemos al dia de los efectos del preset
    397         status.readfp(statusfile)
    398 
    399         # v2.0 Volumen limitado opcional al arranque
    400         limit_level(level_on_startup, max_level_on_startup)
    401 
    402         # V2.0 enlace con el control de volumen ficticio de MPD
    ...
    ...
```

El problema es ser debido a que la consulta `status.readfp(statusfile)` no dispone del archivo `audio/status` completamente actualizado:

    ConfigParser.MissingSectionHeaderError: File contains no section headers.
    file: /home/firtro/audio/status, line: 1
    'f\n'

FIX v1: ponemos un bucle en `initfirtro.py` con una pequeña espera para que `audio/status` esté disponible y la lectura sea exitosa.

2ª parte: ocurre lo mismo en `radio_channel.py`:

```
  File "/home/firtro/bin/radio_channel.py", line 22, in <module>
    from getstatus import *
  File "/home/firtro/bin/getstatus.py", line 15, in <module>
    system_eq = status.get('room EQ', 'system_eq')
  File "/usr/lib/python2.7/ConfigParser.py", line 330, in get
    raise NoSectionError(section)
  ConfigParser.NoSectionError: No section: 'room EQ'
```

**FIX v2:**

Se traslada el bucle de espera al propio módulo **`getstatus.py`**

**A ESTUDIAR:**

Esta situación de problemas de lectura de `audio/status` está relacionada con la aparición por consola del siguiente error:

```
Error while reading command file descriptor 0: Input/output error
Error on command file descriptor 0

```

**Comment by Rsantct** [comment]
se aplica el bucle en **getstatus.py** en la branch **info_display**

**Comment by Rsantct** [comment]
se aplica en bucle tanto en **getstatus.py** como en **initfirtro.py**, en la branch info_display.
